services:
  github-runner:
    build:
      context: .
      dockerfile: dockerfile
      args:
        VERSION: ${VERSION}
        HASH: ${HASH}
        ORGANIZATION: ${ORGANIZATION}
        TOKEN: ${TOKEN}
      
    container_name: self-host-runner
    restart: "always"
    env_file:
      - .env
    volumes:
      - ./data:/data
