services:
  github-runner:
    build:
      context: .
      dockerfile: dockerfile
      args:
        VERSION: ${VERSION}
        HASH: ${HASH}
        ORGANIZATION: ${ORGANIZATION}
        TOKEN: ${TOKEN}
        RUNNER_NAME: ${RUNNER_NAME}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}

    image: localhost/self-host-runner_github-runner
      
    container_name: self-host-runner
    restart: "always"
    env_file:
      - .env
    volumes:
      - ${SOCKET_PATH}:/run/podman/podman.sock
      - ./data:/data
